ujjwalkarn/Machine-Learning-Tutorials

README.md
Added Tensorflow examples for beginners to TensorFlow list
=> Added tensorflow examples

README.md
Added a few blogs/tutorials about deep learning (+ 1 commit for typo)
=> Added deep learning resources

README.md
This is a substantial guide that I wrote on logistic regression, including tons of resource links.
Thanks!
Kevin
=> add logistic regression guide

README.md
I added a direct link to the video from my "ROC and AUC Explained" post.
Thanks!
Kevin
=> add related video link to "ROC and AUC Explained"

README.md
This is an excellent video series by Hastie and Tibshirani, the authors of multiple well-known statistical learning books.
Thanks!
Kevin
=> add link to machine learning videos by Hastie and Tibshirani

README.md
This is a high-quality textbook that I recommend to my data science students.
Thanks!
Kevin
=> add Statistics and Kaggle links

README.md
I added “Top-down learning path: Machine Learning for Software Engineers”
=> Added "Machine Learning for Software Engineers"

README.md
This blog has an interactive visual illustration of neural networks concepts and it's quite useful for ML enthusiasts.
=> Added J Alammar's blog

README.md
Easiest Machine learning Blog by Adam Geitgey
=> Easiest Machine Learning Blog

README.md
Added Have Fun With Machine Learning, an absolute beginner's guide to Machine Learning and Image Classification with Neural Networks https://github.com/humphd/have-fun-with-machine-learning. Also looks like my text editor removed some errant trailing white space.
=> Added 'Have Fun With Machine Learning'

README.md
The links weren't shown properly.
=> Fix Broken Formatting

README.md
Hi, added a link to my github repo that contains machine learning related notebooks. Not sure if this goes in the blog section or if the content's quality meets your standard. Please let me know your thoughts. Thanks!
=> machine learning notebooks

README.md
Hyperopt tutorial for Optimizing Neural Networks’ Hyperparameters:
http://vooban.com/en/tips-articles-geek-stuff/hyperopt-tutorial-for-optimizing-neural-networks-hyperparameters/
=> Add Hyperopt tutorial

README.md
This is a great article on how to use cross-validation for model selection (cross-validate your model selection process)
=> Cross-validate your model selection process

README.md
Looking at the millions of #machinelearning tweets already processed, noise is a little over 94%. Looking at the 8,000 daily tweets that are tagged #machineLearning, the site filters and ranks the most popular shared content in realtime. Machine learning’s zeitgeist, you might say. It's been running for over a year, monitoring half a billion tweets a day, and will always be free to use.
=> Add THL to README.md

README.md
The old link wasn't working anymore.  Replaced with new location.
=> Updated link with new location

README.md
The links for 'Simple Implementation of Genetic Algorithms in Python' were broken.
=> Fix broken genetic algorithms links.

README.md
I added 5 aggregator/awesome repos of graph based deep learning papers, each has a different flavour. The first two include implementations. The last three reference and aggregate only the papers. Also updated the TOC.
=> Created network representation learning section.

README.md
Added a few links about the CatBoost tool. (documentation, tutorials, link to the project, comparison)
=> Added info about Cat Boost in "Boosting" category

README.md
Hello,
This adds [Your Guide to Latent Dirichlet Allocation](https://medium.com/@lettier/how-does-lda-work-ill-explain-using-emoji-108abf40fa7d) to the list.
:+1:
=> Adds Your Guide to Latent Dirichlet Allocation
